apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: docker.io/yuhaibao/aws-awsmid-registry:1.0.18
          env:
            - name: AUTHOR
              value: eureka
          ports:
            - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: awsmid-registry
spec:
  ports:
    - port: 7000
      protocol: TCP
      targetPort: 7000
  type: ClusterIP
  selector:
    app: eureka